server:
  port: 8889
spring:
  application:
    name: mszlu_admin_blog

#数据库的配置
# datasource
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: chenbing
    driver-class-name: com.mysql.cj.jdbc.Driver

  #mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_


